version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: webapp
    image: webapp:v1
    ports:
      - "3000:3000"
  loadbalancer:
    build:
      context: .
      dockerfile: loadbalancer
    image: loadbalancer:v1
    ports:
      - "8080:8080"